"""Add Product table

Revision ID: 278a07d70aec
Revises: 6ebde1934ada
Create Date: 2025-02-25 21:08:46.317053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278a07d70aec'
down_revision = '6ebde1934ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
